language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-propeller' ]; then cd .. && eval "mv $currentfolder generator-propeller" && cd generator-propeller; fi

